DROP DATABASE IF EXISTS examdb;

DROP ROLE IF EXISTS examdb; 

CREATE ROLE haha LOGIN
  ENCRYPTED PASSWORD 'md568cefad35fed037c318b1e44cc3480cf' -- password: pass
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE DATABASE lala WITH OWNER = haha ENCODING = 'UTF8';
   

